[project]
name = 'Gig-Economy-Benefits-Pool'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.benefits-contribution-calculator]
path = 'contracts/benefits-contribution-calculator.clar'
clarity_version = 3
epoch = '3.2'

[contracts.claim-verification-system]
path = 'contracts/claim-verification-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.earnings-tracking-oracle]
path = 'contracts/earnings-tracking-oracle.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
